export const URL = "http://automationpractice.com"
export const homepageSignin = ".login"
export const NewUseremail = "#email_create"
export const RegisterBtn = "#SubmitCreate > span"
export const SelectGender = "#id_gender2"
export const firstNameField = "#customer_firstname"
export const lastNameField = "#customer_lastname"
export const PasswordField = "#passwd"
export const DOBdays = "#days"
export const DOBmonths= "#months"
export const DOByears = "#years"
export const NewsLetter = "#newsletter"
export const Option = "#optin"
export const NewUserAddrerss = "#address1"
export const City = "#city"
export const State = "#id_state"
export const Postcode = "#postcode"
export const PhoneNumber = "#phone_mobile"
export const Alias = "#alias"
export const SubmitBtn = "#submitAccount"
export const Assert = ".logout"

export const Useremail = "#email"
export const Userpassword = "#passwd"
export const SigninBtn = "#SubmitLogin > span"
export const TSHIRTS = '.sf-menu > :nth-child(3) > a'
export const SizeM = "#layered_id_attribute_group_2"
export const AddToCartBtn = '.ajax_add_to_cart_button > span'
export const ProceedToCheckOut = '.button-container > .button-medium > span'
export const ProceedToCheckOutConfirm = '.cart_navigation > .button > span'
export const TermsOfService = "#cgv"
export const BankWirePayment = '.bankwire'
export const ConfirmMyOrder = '#cart_navigation > .button > span'
export const OrderConfirmation = '.page-heading'
